version: '3.5'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    # networks:
    #   - license_backend
  db.license:
    image: postgres:15.2-alpine
    container_name: db.license
    ports:
      - "${HOST:-127.0.0.1}:5431:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      #- ./data/sql:/sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cypasword
      - POSTGRES_DB=licenses
    restart: always   
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    # networks:
    #   - license_backend

  redis.license:
    image: redis:7.2-rc1-alpine
    container_name: redis.license
    # command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${HOST:-127.0.0.1}:6378:6379"
    restart: always   
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    # networks:
    #   - license_backend
networks:
  license_backend:
    external: true
volumes:
  dbdata:
    driver: local
  pgadmin-data:
    driver: local